### PR TITLE
Laravel 9 support

### PR DESCRIPTION
**Pull request by stephenjude**
- Add Laravel 9 support

### CODE REVIEW

**Comment by stephenjude** [comment]
@f9web please review

**Comment by ultrono** [comment]
Wow, I was literally planning to add this later today. Thanks for PR, will run the tests now. If they pass will merge ASAP.

**Comment by stephenjude** [comment]
Thanks @ultrono

**Comment by ultrono** [comment]
OK all tests passing. If you can just update the read me file to reflect the fact the package also supports Laravel 9 I'll merge now 👍

**Comment by ultrono** [comment]
@stephenjude Apologies, can you also update https://github.com/f9webltd/laravel-api-response-helpers/blob/master/.github/workflows/run-tests-laravel-8.yml to include Laravel v9 - this will cause the automated tests to run on Laravel 9. At the moment they're only running on up to Laravel 8. If you;re unable to do this please let me know and I'll action now.

**Comment by stephenjude** [comment]
@ultrono okay

**Comment by ultrono** [comment]
> @ultrono okay

No probs, got to pop out now, but will check this PR when I get back in 🚀

**Comment by stephenjude** [comment]
@ultrono I have updated the workflow and the readme. You can check when you get back.

**Comment by ultrono** [comment]
Great can see your changes and all tests are passing on Laravel 9 now. Pretty sure we can avoid creating a new GitHub action just for Laravel 9, but I'll handle that later.

**Comment by stephenjude** [comment]
Alright @ultrono

**Pull request merged**
