### PR TITLE
chore: add config files and update `composer.json` test script

### PR DESCRIPTION
**Pull request by chapeupreto**
This commit adds the following config files:

- .editorconfig
- .gitattributes
- phpunit.xml.dist

and also update `composer.json` test script so it can use `phpunit.xml.dist`

> P.S.: I know this is a small contribution, but could you please add a `hacktoberfest-accepted` label on it? I really appreciate it!

### CODE REVIEW

**Comment by ultrono** [comment]
@chapeupreto thanks for the PR. I'll be doing some work on this in next couple of days and merging in a few other PRs. I'll be sure to add your label too 👍

**Comment by ultrono** [comment]
When running the tests with the new phpunit file there is some new output: 

````
   Warning - The configuration file did not pass validation!
  The following problems have been detected:

  Line 20:
  - Element 'phpunit', attribute 'failOnEmptyTestSuite': The attribute 'failOnEmptyTestSuite' is not allowed.

  Line 26:
  - Element 'coverage': This element is not expected.

  Test results may not be as expected.
```

The tests do all pass, but it would be good to remove the errors / warning relating to the new phpunit file 👍

**Comment by chapeupreto** [comment]
@ultrono You're entirely right. 

I think those warnings are due to PHP version 7.4

When you run the tests using PHP 8.0+ there are no such errors.

My bad 'cause I missed those constraints in `composer.json` file. However, I think we should just use `^9.0` as the PHPUnit constraint because both PHP7.4 and PHP8.0 can support it.

Also, I think we shouldn't  commit `composer.lock`.

I added new commits removing `composer.lock` and also changing the PHPUnit constraint to use `^9.0`.

I did some tests running PHP8.0 and PHP7.4 and everything seems ok now (without the need to change the `phpunit.xml.dist` config file):

**PHP8:**

Screenshot from 2021-10-04 16-54-14

**PHP7.4:**

Screenshot from 2021-10-04 16-55-43

I'd love to hear your thoughts!

**Comment by JacekAndrzejewski** [comment]
> Also, I think we shouldn't commit `composer.lock`.

That's right, this is a library and composer.lock shouldn't be commited and it should be in gitignore. I didn't even realize it was there.
[Here's](https://blog.martinhujer.cz/17-tips-for-using-composer-efficiently/#tip-%236%3A-put-%60composer.lock%60-into-%60.gitignore%60-in-libraries) a good explanation why it should be that way.

**Comment by ultrono** [comment]
Merged and label added as requested! Thanks @chapeupreto

**Pull request merged**
