### PR TITLE
File response trait

### PR DESCRIPTION
**Pull request by gogl92**
Finally, I got some time to work on this, I'm not sure if this is the correct approach but I decided to create a new trait for file-related operations. Please let me know your thoughts.

For #21

### CODE REVIEW

**Comment by gogl92** [comment]
Whenever you have chance please take a look @ultrono 👍🏼

**Comment by ultrono** [comment]
Thanks the PR :+1: 

A quick look at the failures relate to PHPversions. Remeber this package supports PHP 7.4 and up - I can see you;ve used named arguements. There also appear tio be some missing imports within the tests you've added.

Semi related, are you able to update the read too?

**Comment by ultrono** [comment]
Unsure if a 180KB mock image is required? Can a tony pixel image be used?

Again it may be my own experience, but I've never seen an API return a full file response. Full file responses are typically for a web controller. I've seen things like the below, but not a full response. Do you have some examples this package is essentially a wrapper around `response()->json()`? Again, this may be down to fact I've peraonally never seen an API return a full file response.

```
return $this->respondWithSuccess([
   'name' => 'file.png'
   'size' => 123456,
   'mime' => 'application/pdf',
   'path' => 'https://cdn.site.co.uk/file.png',
   // etc.
]);
```

**Comment by ultrono** [comment]
For clarity something such as the following is what I was semi expecting. To fetch file details, we could call methods from the `Illuminate\Contracts\Filesystem\Filesystem`interface.

```php
return $this->respondWithFile('assets/invoice.pdf', 's3');
```

The response itself would use method from the `Illuminate\Support\Facades\Storage`facade:

```php
use Illuminate\Support\Facades\Storage;

function respondWithFile(string $path, string $disk) {
   $driver = Storage::dsk($disk);

   return $this->apiResponse([
       'size' => $driver->size($path),
       'url' => $driver->url($path),
       'name' => basename($path),
       'last_modified' => $driver->lastModified($path),
       // etc.
   ]);
}

```

**Comment by gogl92** [comment]
@ultrono Hi, ok let me address your comments and check with PHP 7.4, I'll update the README as well.

**Comment by ultrono** [comment]
Couple of other points.

Would prefer the separate trait you've created be part of the main trait, I think a separate trait is not necessary here. The package now also depends upon `illuminate/filesystem`, meaning the composer file should be updated accordingly. To avoid creating a new exception, can we use one of the standard Laravel exceptions, such as `Illuminate\Contracts\Filesystem\FileNotFoundException`? All code should be formatted to PSR-12 also.

Cheers

**Pull request closed without merging**
